model:
  model_name: "energy_based_learning.pth"
  steps: 1
  alpha: 300 # 1/steps
  model_name: "ebt.pth"

# Trainer config for contrastive
contrastive:
  steps: 60 
  alpha: 10
  reg_coef: 0.01 

# Trainer config for ebt
ebt:
  steps: 50
  alpha: 10
  clamp_grad: 0.03

# Trainer config for ired
ired:
  num_landscapes: 10
  sigma_max: 0.95
  sigma_min: 0.01
  neg_corruption_scale: 0.5
  neg_refine_steps: 2
  neg_refine_step_size: 0.2
  mse_weight: 1.0
  reg_coef: 0.00001
  contrastive_temperature: 5.0
  energy_dim: 1

memory:
  num_workers: 8

training:
  # Adam Optimization
  learning_rate: 0.001
  weight_decay: 0.01
  gradient_accumulation_steps: 1
  max_grad_norm: 2.0 # don't do massive updates

  # Training Params
  epochs: 3
  checkpoint_dir: "./checkpoints"
  save_steps: 200
  num_episodes: 100
  batch_size: 16
  print_every: 4
  device: "cuda" # I am on a mac; MPS = Metal Performance Shader

inference:
  samples: 8

wandb:
  project: "EBM"
  entity: "eshaanb"
  name: "EBM"
  notes: "EBM"
