_wandb:
    value:
        cli_version: 0.24.0
        e:
            qnhm8itgk8xzv0ugrpyn6est74p2nyr1:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "470306373632"
                        used: "63234310144"
                executable: /simurgh/u/eshaanb/3DReconstr/3d_venv/bin/python3
                git:
                    commit: b7c1b2639a064e27e0f838fe7407937e6cf8205e
                    remote: https://github.com/7peng/lean-ebm/
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-ed8253cb-9ad7-dae0-3bde-3efa9f9f45f1
                host: simurgh5.stanford.edu
                memory:
                    total: "1623030444032"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /simurgh/u/eshaanb/ebm-experiments/main.py
                python: CPython 3.12.3
                root: /simurgh/u/eshaanb/ebm-experiments
                slurm:
                    job_id: "14680576"
                startedAt: "2026-03-03T05:18:53.117660Z"
                writerId: qnhm8itgk8xzv0ugrpyn6est74p2nyr1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 50
                - 71
                - 105
            "2":
                - 1
                - 41
                - 49
                - 50
                - 71
                - 105
            "3":
                - 13
            "4": 3.12.3
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
contrastive:
    value: '{''steps'': 60, ''alpha'': 10, ''reg_coef'': 0.01}'
ebt:
    value: '{''steps'': 50, ''alpha'': 10, ''clamp_grad'': 0.03}'
inference:
    value: '{''samples'': 8}'
memory:
    value: '{''num_workers'': 8}'
model:
    value: '{''model_name'': ''ebt.pth''}'
training:
    value: '{''learning_rate'': 0.001, ''weight_decay'': 0.01, ''gradient_accumulation_steps'': 1, ''max_grad_norm'': 2.0, ''epochs'': 3, ''checkpoint_dir'': ''./checkpoints'', ''save_steps'': 200, ''num_episodes'': 100, ''batch_size'': 16, ''print_every'': 4, ''device'': ''cuda''}'
wandb:
    value: '{''project'': ''EBM'', ''entity'': ''eshaanb'', ''name'': ''EBM'', ''notes'': ''EBM''}'
