model:
  steps: 1
  alpha: 300 # 1/steps
  model_name: "ired.pth"

# Trainer config for contrastive
contrastive:
  steps: 60 
  alpha: 10
  reg_coef: 0.01 

# Trainer config for ebt
ebt:
  steps: 40
  alpha: 15
  clamp_grad: 0.03

# Trainer config for ired
ired:
  energy_dim: 1

  # noise params
  num_landscapes: 50 
  sigma_max: 0.99
  sigma_min: 0.001
  neg_corruption_scale: 0.5 # how noisy we want our negative sample to be

  # refine steps after we noise
  neg_refine_steps: 0
  neg_refine_step_size: 0

  # loss weight
  mse_weight: 1.0
  reg_coef: 1e-6
  contrastive_weight: 1e-6

memory:
  num_workers: 8

training:
  # Adam Optimization
  learning_rate: 3e-4
  weight_decay: 0.0
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0 # don't do massive updates

  # Training Params
  epochs: 10
  checkpoint_dir: "./checkpoints"
  save_steps: 200
  batch_size: 32
  print_every: 4
  device: "mps" # I am on a mac; MPS = Metal Performance Shader

inference:
  samples: 8

wandb:
  project: "EBM"
  entity: "eshaanb"
  name: "EBM"
  notes: "EBM"
